languageCode: en-GB
locale: en-GB
title: The Impact Orbit Creative Group Handbook
baseURL: "https://handbook.impactorbit.co/"

enableRobotsTXT: true
enableGitInfo: true
canonifyURLs: true
pluralizeListTitles: false
enableEmoji: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  title: The Impact Orbit Creative Handbook
  social:
    twitter: impactorbitco
  defaultContentLanguage: en
  locale: en-GB
  description: Learn more about Impact Orbit and what makes us tick.
  search:
    algolia:
      appId: 3IIMMA8IDY
      apiKey: 71feb3efa6044f78ab6b8a7422e727b7
      indexName: handbook-impactorbit
  images:
    - images/impactorbit-cover.png
  branch: main
  project: impactorbitco/handbook-main
  repoid: 42817607
  plantuml:
    enable: true
  mermaid:
    enable: true
  offlineSearch: false
  ui:
    sidebar_menu_compact: false
    sidebar_menu_foldable: true
    sidebar_cache_limit: 1000
    sidebar_menu_truncate: 0
    navbar_logo: true
    footer_about_disable: true
    showLightDarkModeMenu: true
  copyright: "Impact Orbit Creative Group"
  privacy_policy: https://about.impactorbit.co/privacy/
  links:
    user:
      - name: "Slack"
        url: "https://slack.impactorbit.co"
        icon: "fab fa-slack"
        desc: "#handbook on Slack"
      - name: "Repository"
        url: "https://github.com/impactorbitco/handbook-main"
        icon: "fa-solid fa-code-branch"
        desc: "GitHub project"
      - name: "Edit the site"
        url: "/docs/development"
        icon: "fa-solid fa-edit"
        desc: "Contribute to the handbook"
    developer: []

caches:
  getresource:
    dir: :cacheDir/:project
    maxAge: 24h

staticDir:
  - static
  - data
  - assets

menu:
  main:
    - weight: -2
      name: Impact Orbit
      url: https://about.impactorbit.co/
      pre: '<i class="fab fa-gitlab"></i>'

mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes: [""]

outputs:
  home: ["HTML", "REDIRECTS"]
  section: ["HTML"]

outputformats:
  redirects:
    baseName: "_redirects"
    isPlainText: true
    mediaType: "text/netlify"
    notAlternative: true

markup:
  goldmark:
    renderHooks:
      link:
        useEmbedded: fallback
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    tabWidth: 2
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false

security:
  funcs:
    getenv: ["^HUGO_", "PERISCOPE_EMBED_API_KEY", "PRODUCT_ANALYTICS_APP_KEY", "PRODUCT_ANALYTICS_HOST", "PUBLIC_HANDBOOK_REF"]

module:
  proxy: https://proxy.golang.org
  hugoVersion:
    extended: true
    min: 0.123
  imports:
    - path: github.com/impactorbitco/handbook-main
      disable: false
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false

ignoreErrors:
  - error-tweet-failed

timeout: "300s"