# NOTE: Static Sites often want to optimize for fast build and deploy
#       pipeline times, so changes are published as quickly as possible.
#       Therefore, this default config includes optional variables, settings,
#       and caching, which help minimize job run times. For example,
#       disabling support for git LFS and submodules. There are also retry
#       and reliability settings which help prevent false build failures
#       due to occasional infrastructure availability problems. These are
#       all documented inline below, and can be changed or removed as
#       necessary, depending on the requirements for your repo or project.

###################################
#
# GENERAL/DEFAULT CONFIG:
#
###################################

stages:
  - sync
  - build
  - deploy
  - notify
  - maintenance

include:
  - component: gitlab.com/components/secret-detection/secret-detection@~latest
  - component: gitlab.com/gitlab-org/components/danger-review/danger-review@1.4.1
    inputs:
      job_stage: notify

default:
  image: alpine:latest
  interruptible: true # All jobs are interruptible by default
  # The following 'retry' configuration settings may help avoid false build failures
  #  during brief problems with CI/CD infrastructure availability
  retry:
    max: 2 # This is confusing but this means "3 runs at max".
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
      - job_execution_timeout
      - stuck_or_timeout_failure
  tags:
    - saas-linux-medium-amd64
  cache:
    - key:
        files:
          - go.mod
          - go.sum
      paths:
        - $GOPATH/pkg/mod/
    - key:
        files:
          - package.json
          - package-lock.json
      paths:
        - $NPM_CACHE
    - key:
        files:
          - go.sum
      paths:
        - $HUGO_CACHEDIR

variables:
  # NOTE: The following PERFORMANCE and RELIABILITY variables are optional, but may
  #       improve performance of larger repositories, or improve reliability during
  #       brief problems with CI/CD infrastructure availability

  ### PERFORMANCE ###
  # GIT_* variables to speed up repo cloning/fetching
  GIT_DEPTH: 0
  # Disabling LFS and submodules will speed up jobs, because runners don't have to perform
  # the submodule steps during repo clone/fetch. These settings can be deleted if you are using
  # LFS or submodules.
  GIT_LFS_SKIP_SMUDGE: 1
  GIT_SUBMODULE_STRATEGY: none

  # Speed up artifact compression and upload
  # https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/2684
  FF_USE_FASTZIP: 1
  ARTIFACT_COMPRESSION_LEVEL: fast

  ### RELIABILITY ###
  # Reduce potential of flaky builds via https://docs.gitlab.com/ee/ci/yaml/#job-stages-attempts variables
  GET_SOURCES_ATTEMPTS: 3
  ARTIFACT_DOWNLOAD_ATTEMPTS: 3
  RESTORE_CACHE_ATTEMPTS: 3
  EXECUTOR_JOB_SECTION_ATTEMPTS: 3

  ### BUILD / PAGES DEFAULTS **
  ENVIRONMENT: 'production'
  HUGO_BASEURL: 'https://handbook.gitlab.com/'
  PAGES_PREFIX: ""

  ### TOOLING ###
  # Specify versions of tools used in pipelines
  HUGO_VERSION: '0.151.0'
  HUGO_IMAGE: "docker.io/hugomods/hugo:exts-$HUGO_VERSION"
  HUGOLINT_VERSION: '2.0.3'
  MARKDOWNLINT_VERSION: '0.18.1'
  VALE_VERSION: '3.13.0'

  ### CACHE DEPENDENCIES ###
  GOPATH: $CI_PROJECT_DIR/.GOPATH
  NPM_CACHE: $CI_PROJECT_DIR/.npm
  HUGO_CACHEDIR: $CI_PROJECT_DIR/.hugo_cache

.default-branch: &default-branch
  if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUILD_AND_TEST_ONLY != "true"

.merge-request-only: &merge-request-only
  if: $CI_PIPELINE_SOURCE == 'merge_request_event'

.merge-request-or-tag: &merge-request-or-tag
  if: '$CI_MERGE_REQUEST_IID || $CI_COMMIT_TAG'

.scheduled-pipeline: &scheduled-pipeline
  if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_DEPLOY == "true"'

.build-and-test-only: &build-and-test-only
  if: '$BUILD_AND_TEST_ONLY == "true"'

.is-fork: &is-fork
  if: '$CI_PROJECT_ID != "42817607"'

.scheduled-update: &scheduled-update
  if: '$CI_PIPELINE_SOURCE == "schedule" && $RUN_TYPE == "count-update"'

.skip-bot-authored: &skip-bot-authored
  if: '$GITLAB_USER_LOGIN =~ /^(project|group)_/'
  when: never
###################################
#
# JOB TEMPLATES
#
###################################

.glab_job:
  image:
    name: gitlab/glab
    entrypoint: [""]
  before_script:
    - apk update
    - apk upgrade
    - apk add bash git jq sed

.linting_notification_job:
  extends: .glab_job
  needs: ["markdownlint", "handbooklint", "vale", "hugolint"]
  stage: notify
  rules:
    # Skip if MR is authored by a project or group access token
  - <<: *skip-bot-authored
    # Otherwise run the job as usual
  - <<: *merge-request-or-tag

###################################
#
# INTERRUPTION PROTECTION
#
###################################

dont-interrupt-me:
  stage: sync
  interruptible: false
  script:
    - echo "This jobs makes sure this pipeline won't be interrupted! See https://docs.gitlab.com/ee/ci/yaml/#interruptible."
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"

###################################
#
# BUILD STAGE
#
###################################

build:
  image: $HUGO_IMAGE
  stage: build
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:group1\r\e[0KGroup 1"
    - apk update
    - echo -e "\e[0Ksection_end:`date +%s`:group1\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:group2\r\e[0KGroup 2"
    - apk upgrade
    - echo -e "\e[0Ksection_end:`date +%s`:group2\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:group3\r\e[0KGroup 3"
    - apk add go npm yq curl coreutils sed
    - echo -e "\e[0Ksection_end:`date +%s`:group3\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:group4\r\e[0KGroup 4"
    - scripts/sync-data.sh
    - echo -e "\e[0Ksection_end:`date +%s`:group4\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:group5\r\e[0KGroup 5"
    - npm ci --cache $NPM_CACHE
    - echo -e "\e[0Ksection_end:`date +%s`:group5\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:group6\r\e[0KGroup 6"
    - hugo --enableGitInfo
    - echo -e "\e[0Ksection_end:`date +%s`:group6\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:group7\r\e[0KGroup 7"
    - find "public" -type f -name '*.html' -exec sed -i -e "s/content-sites\/handbook\/${PAGES_PREFIX}\/content-sites\/handbook\/${PAGES_PREFIX}/content-sites\/handbook\/${PAGES_PREFIX}/g" {} +
    - echo -e "\e[0Ksection_end:`date +%s`:group7\r\e[0K"
    - echo "CI_PAGES_URL ${CI_PAGES_URL}"
    - echo "PAGES_PREFIX ${PAGES_PREFIX}"
    - echo "Base URL build ${CI_PAGES_URL}/$PAGES_PREFIX/"
    - echo "Verify base URL ${HUGO_BASEURL}"
  artifacts:
    paths:
      - public
  rules:
  - <<: *default-branch
  - <<: *build-and-test-only
  - <<: *merge-request-only
    variables:
      PAGES_PREFIX: 'mr$CI_MERGE_REQUEST_IID'
      HUGO_BASEURL: "${CI_PAGES_URL}/${PAGES_PREFIX}/"

###################################
#
# DEPLOY STAGE
#
###################################
pages:
  stage: deploy
  dependencies: [build]
  environment:
    name: $ENVIRONMENT
    url: $HUGO_BASEURL
  variables:
    GIT_STRATEGY: none
  pages:
    path_prefix: "$PAGES_PREFIX"
  artifacts:
    paths:
      - public
  script:
    - echo "CI_PAGES_URL ${CI_PAGES_URL}"
    - echo "PAGES_PREFIX ${PAGES_PREFIX}"
    - echo "Pages accessible through ${HUGO_BASEURL}"
  rules:
    - <<: *default-branch
    - <<: *scheduled-pipeline
    - if: '$CI_MERGE_REQUEST_LABELS =~ /deploy-review-app-always/'
      variables:
        PAGES_PREFIX: 'mr$CI_MERGE_REQUEST_IID'
        ENVIRONMENT: 'review/mr$CI_MERGE_REQUEST_IID'
        HUGO_BASEURL: "${CI_PAGES_URL}/"
    - <<: *merge-request-only
      variables:
        PAGES_PREFIX: 'mr$CI_MERGE_REQUEST_IID'
        ENVIRONMENT: 'review/mr$CI_MERGE_REQUEST_IID'
        HUGO_BASEURL: "${CI_PAGES_URL}/"
      when: manual
      allow_failure: true

####################################
##
## TEST STAGE
##
####################################

markdownlint:
  image:
    name: davidanson/markdownlint-cli2:v${MARKDOWNLINT_VERSION}
    entrypoint: [""]
    docker:
      user: root
  stage: build
  needs: []
  variables:
    FORCE_COLOR: 1
  before_script:
    - npm install chalk terminal-link
    - apk add git bash
  script:
    - scripts/markdownlint.sh
  rules:
    - <<: *merge-request-or-tag
    - <<: *is-fork
  artifacts:
    when: always
    expire_in: 1 month
    paths:
      - markdownlint-cli2-codequality.json
    reports:
      codequality: markdownlint-cli2-codequality.json

vale:
  image:
    name: jdkato/vale:v${VALE_VERSION}
    entrypoint: [""]
    docker:
      user: root
  stage: build
  needs: []
  before_script:
    - apk add git bash
  script:
    - scripts/vale.sh
  rules:
    - <<: *merge-request-or-tag
    - <<: *is-fork
  artifacts:
    when: always
    expire_in: 1 month
    paths:
      - vale-codequality.json
    reports:
      codequality: vale-codequality.json

handbooklint:
  extends: .glab_job
  stage: build
  needs: []
  script:
    - scripts/handbook-lint.sh
  rules:
    - <<: *merge-request-or-tag
    - <<: *is-fork
  artifacts:
    when: always
    expire_in: 1 month
    paths:
      - handbook-codequality.json
    reports:
      codequality: handbook-codequality.json

check_path_change:
  extends: .glab_job
  stage: build
  script:
    - scripts/check-path-change.sh
  rules:
      # Skip if MR is authored by a project or group access token
    - <<: *skip-bot-authored
    - if: $CI_MERGE_REQUEST_LABELS =~ /skip-path-check/
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_PROJECT_ID != $CI_PROJECT_ID
      when: never
    - <<: *is-fork
      when: never
    - if: $CI_MERGE_REQUEST_EVENT_TYPE == 'merge_train'
      when: never
    - <<: *merge-request-only

hugolint:
  stage: build
  needs: []
  rules:
    - <<: *build-and-test-only
    - <<: *is-fork
    - <<: *default-branch
    - <<: *merge-request-or-tag
  image:
    name: registry.gitlab.com/gitlab-com/content-sites/handbook-tools/hugolint:v${HUGOLINT_VERSION}
  before_script:
    - apk add jq curl
  script:
    - hugolint linkcheck --config .hugolint.yaml --format=json $(find content -type f -name '*.md' | grep -v ' ') >linkcheck.json
    - |
      # Compare with target branch when running as a merge request pipeline.
      if [ "${CI_PIPELINE_SOURCE}" == "merge_request_event" ]; then
        hugolint codequality latest --project "42817607" --artifact 'linkcheck.json' >'latest.json'
        # additional JSON file to populate MR comment in post_comment_on_failure job
        echo '[]' > new_broken_links.json
        jq -s '.[1] - .[0]' latest.json linkcheck.json > new_broken_links.json
        hugolint codequality diff --exit-code 'latest.json' 'linkcheck.json'
      fi
  artifacts:
    when: always
    expire_in: 1 month
    paths:
      - linkcheck.json
      - new_broken_links.json
    reports:
      codequality: linkcheck.json

secret_detection:
  stage: build
  needs: []
  dependencies: [] # Don't download artifacts, especially `./public/`
  rules:
    - <<: *build-and-test-only
    - <<: *merge-request-or-tag
    - <<: *is-fork

####################################
##
## NOTIFY STAGE
##
####################################

# override danger-review component rules
danger-review:
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    changes:
      paths:
        - content/handbook/engineering/architecture/**/*
        - static/images/engineering/architecture/**/*
      compare_to: 'main'

post_comment_on_failure:
  extends: .linting_notification_job
  when: on_failure
  script:
    - scripts/parse-codequality-report.sh -r ./codequality.json > msg.txt
    - scripts/post-comment.sh "$(cat msg.txt)"

resolve_comment_on_success:
  extends: .linting_notification_job
  when: on_success
  script:
    - scripts/resolve-comment.sh

notify_slack_on_build_failures:
  when: on_failure
  stage: notify
  script: scripts/send-failure-notification-to-slack.sh
  rules:
  - <<: *is-fork
    when: never
  - <<: *default-branch

####################################
##
## MAINTENANCE STAGE
##
####################################

update_counts:
  stage: maintenance
  before_script:
    - apk add git
  script: scripts/update-counts.sh
  rules:
  - <<: *scheduled-update
